apiVersion: apps/v1
kind: Deployment
metadata:
  name: aurora-frontend
  namespace: aurora
  labels:
    app: aurora-frontend
spec:
  replicas: 2  # Can scale frontend horizontally
  selector:
    matchLabels:
      app: aurora-frontend
  template:
    metadata:
      labels:
        app: aurora-frontend
    spec:
      containers:
      - name: aurora-frontend
        image: ghcr.io/blueandhack/aurora/aurora-frontend:latest  # GitHub Container Registry
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 3
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: aurora-frontend
  namespace: aurora
  labels:
    app: aurora-frontend
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: aurora-frontend
  type: ClusterIP